#' Creates pie charts with the fraction of each hashing barcode
#' @param VDJ.matrix Output of the VDJ_GEX_matrix function
#' @param group.by  Character. Defaults to "sample_id". Column name of VDJ.matrix to split VDJ.matrix by. For each unique entry in that column separate plots will be generated. Therefore plots can be generated by sample_id, group_id or any other metadata item.To get plots for the whole repertoire set group.by to "none".
#' @param label.size Size of the labels showing the count for each hashing barcode
#' @return returns a list containing plots fro VDJ in output[[1]] and GEX in output[[2]]
#' @export
#' @examples
#' \dontrun{
#' Cell_hashing_piecharts(VDJ.matrix = VDJ_comb_gex, group.by ="sample_id",label.size = 4,nudge_x = 1.5)
#'}


Cell_hashing_piecharts <- function(VDJ.matrix, group.by,label.size){
  
  
  require(stringr)
  require(ggplot2)
  require(stringdist)
  require(tidyverse)
  
  #define default parameters if not specified 
  if(missing(group.by)) group.by <- 'sample_id'
  if(missing(label.size)) label.size <- 4
  outlist <- list()
  
  #outlist <- list()
  
  if(class(VDJ.matrix[[1]]) == "data.frame"){ ##START VDJ
    if (group.by == 'none') {
      #data is analyzed as a whole
      vdj_split <- VDJ.matrix[[1]]
      VDJ.matrix[[1]]$FB_assignment[is.na(VDJ.matrix[[1]]$FB_assignment)]
    } else if (group.by %in% names(VDJ.matrix[[1]])) {
      #Format the FB_assignment names
      VDJ.matrix[[1]]$FB_assignment <- substr(VDJ.matrix[[1]]$FB_assignment,4,nchar(VDJ.matrix[[1]]$FB_assignment))
      VDJ.matrix[[1]]$FB_assignment[is.na(VDJ.matrix[[1]]$FB_assignment)] <- "Not assignable"
      VDJ.matrix[[1]]$FB_assignment[VDJ.matrix[[1]]$FB_assignment == " assignable"] <- "Not assignable"
      #subset data by group.by
      vdj_split <- split(VDJ.matrix[[1]], VDJ.matrix[[1]][,group.by])
    } else {
      stop("Please provide a valid column name of the VDJ.matrix in group.by")
    }
    
    #iterate over vdj_split
    vdj.plot <- list()
    for (i in 1:length(vdj_split)){
      #Make a table of FB_assignment) columns
      vdj.table <- table(vdj_split[[i]]$FB_assignment)
      vdj.table <- data.frame(group = vdj.table)
      names(vdj.table) <- c("Hashing barcode","count")
      levels(vdj.table$`Hashing barcode`) <- c("Not assignable",levels(vdj.table$`Hashing barcode`)[levels(vdj.table$`Hashing barcode`) != "Not assignable"])
      
      vdj.table2 <- mutate(vdj.table ,csum = rev(cumsum(rev(count))), 
                           pos = count/2 + lead(csum, 1),
                           pos = if_else(is.na(pos), count/2, pos))
      
      vdj.plot[[i]] <- ggplot(vdj.table, aes(x = "" , y = count, fill = fct_inorder(`Hashing barcode`))) +
        geom_col(width = 1) +
        coord_polar(theta = "y") +
        scale_fill_manual(values=c("grey",scales::hue_pal()(length(unique(vdj.table$`Hashing barcode`))-1))) +
        ggrepel::geom_label_repel(data = vdj.table2,
                                  aes(y = pos, label = paste0(count)),
                                  size = label.size, nudge_x = 1.2, show.legend = FALSE,col = "black") +
        guides(fill = guide_legend(title = "Hashing barcode")) +
        theme_void() + theme(plot.title = element_text(hjust = 0.5)) + ggtitle(paste0(vdj_split[[i]][,group.by][1]," (VDJ)"))
    }
    outlist[[1]] <- vdj.plot
  } ##STOP VDJ
  
  if(class(VDJ.matrix[[2]]@meta.data) == "data.frame"){ ##START GEX
    if (group.by == 'none') {
      #data is analyzed as a whole
      VDJ.matrix[[2]]@meta.data$FB_assignment[is.na(VDJ.matrix[[2]]@meta.data$FB_assignment)] <- "Not assignable"
      VDJ.matrix[[2]]@meta.data$FB_assignment[VDJ.matrix[[2]]@meta.data$FB_assignment == " assignable"] <- "Not assignable"
      gex_split <- VDJ.matrix[[2]]@meta.data
    } else if (group.by %in% names(VDJ.matrix[[2]]@meta.data)) {
      #Format the FB_assignment.y names
      VDJ.matrix[[2]]@meta.data$FB_assignment <- substr(VDJ.matrix[[2]]@meta.data$FB_assignment,4,nchar(VDJ.matrix[[2]]@meta.data$FB_assignment))
      VDJ.matrix[[2]]@meta.data$FB_assignment[is.na(VDJ.matrix[[2]]@meta.data$FB_assignment)] <- "Not assignable"
      VDJ.matrix[[2]]@meta.data$FB_assignment[VDJ.matrix[[2]]@meta.data$FB_assignment == " assignable"] <- "Not assignable"
      #subset data by group.by
      gex_split <- split(VDJ.matrix[[2]]@meta.data, VDJ.matrix[[2]]@meta.data[,group.by])
    } else {
      stop("Please provide a valid column name of the VDJ.matrix in group.by")
    }
    
    #iterate over gex_split
    gex.plot <- list()
    for (i in 1:length(gex_split)){
      #Make a table of FB_assignment.y) columns
      gex.table <- table(gex_split[[i]]$FB_assignment)
      gex.table <- data.frame(group = gex.table)
      names(gex.table) <- c("Hashing barcode","count")
      levels(gex.table$`Hashing barcode`) <- c("Not assignable",levels(gex.table$`Hashing barcode`)[levels(gex.table$`Hashing barcode`) != "Not assignable"])
      gex.table2 <- mutate(gex.table ,csum = rev(cumsum(rev(count))), 
                           pos = count/2 + lead(csum, 1),
                           pos = if_else(is.na(pos), count/2, pos))
      
      gex.plot[[i]] <- ggplot(gex.table, aes(x = "" , y = count, fill = fct_inorder(`Hashing barcode`))) +
        geom_col(width = 1) +
        coord_polar(theta = "y") +
        scale_fill_manual(values=c("grey",scales::hue_pal()(length(unique(gex.table$`Hashing barcode`))-1))) +
        ggrepel::geom_label_repel(data = gex.table2,
                                  aes(y = pos, label = paste0(count)),
                                  size = label.size, nudge_x = 1.2, show.legend = FALSE,col = "black") +
        guides(fill = guide_legend(title = "Hashing barcode")) +
        theme_void() + theme(plot.title = element_text(hjust = 0.5)) + ggtitle(paste0(gex_split[[i]][,group.by][1]," (GEX)"))
    }
    outlist[[2]] <- gex.plot
  } ##STOP GEX
  return(outlist)
}#stop function








