#' Produces a barplot with the most frequently used IgH and IgK/L Vgenes.
#' @param VDJ Either (for platypus version "v2") output from VDJ_analyze function. This should be a list of clonotype dataframes, with each list element corresponding to a single VDJ repertoire, OR (for platypus version "v3") the the VDJ matrix output of the VDJ_GEX_matrix() function (VDJ.GEX.matrix.output[[1]])
#' @param HC.gene.number Numeric value indicating the top genes to be displayed. Can be set to "all" to get all HC V genes. If this number is higher than the total number of unique HC V genes in the VDJ repertoire, then this number is equal to the number of unique HC V genes. Default is set to 30.
#' @param LC.Vgene Logical indicating whether to make a barplot of the LC V genes distribution. Default is set to FALSE.
#' @param LC.gene.number Numeric value indicating the top genes to be displayed. Can be set to "all" to get all LC V genes.If this number is higher than the total number of unique LC V genes in the VDJ repertoire, then this number is equal to the number of unique LC V genes. Default is set to 30.
#' @param platypus.version Character. Defaults to "v3". Can be "v2" or "v3" dependent on the input format
#' @param platypus.version Character. Defaults to "v3". Can be "v2" or "v3" dependent on the input format
#' @param group.by  Character. Defaults to "sample_id". Column name of VDJ.matrix to split VDJ.matrix by. For each unique entry in that column separate plots will be generated. Therefore plots can be generated by sample_id, group_id or any other metadata item.
#' @param compare Logical indicating if a plot should be made comparing the occurrence of V genes that are most prominent on average across all samples. Default is set to FALSE.
#' @return Returns a list of ggplot objects which show the distribution of IgH and IgK/L V genes for the most used V genes.
#' @export
#' @examples
#' \dontrun{
#' VDJ_Vgene_usage_barplot(VDJ = VDJ_comb_gex[[1]], platypus.version = "v3", HC.gene.number = 20, LC.Vgene = TRUE, LC.gene.number = 20,compare = TRUE,group.by ="sample_id")
#'}

VDJ_Vgene_usage_barplot <- function(VDJ,
                                    HC.gene.number,
                                    LC.Vgene,
                                    LC.gene.number,
                                    group.by,
                                    platypus.version, 
                                    compare){
  
  Vgene <- NULL
  Percentage <- NULL
  Nr_of_VDJ_chains <- NULL
  Nr_of_VJ_chains <- NULL
  sample_id <- NULL
  HC_Vgene_usage <- list()
  HC_Vgene_usage_plot <- list()
  LC_Vgene_usage <- list()
  LC_Vgene_usage_plot <- list()
  if(missing(LC.Vgene)) LC.Vgene <- FALSE
  if(missing(platypus.version)) platypus.version <- "v3"
  if(missing(compare)) compare <- FALSE
  if(missing(group.by)) group.by <- sample_id
  if(missing(HC.gene.number)) HC.gene.number <- 30
  if(missing(LC.gene.number)) LC.gene.number <- 30
  
  
  #naming compatibility
  VDJ.matrix <- VDJ
  VDJ <- NULL
  if(platypus.version == "v2"){

    clonotype.list <- VDJ.matrix

    for (i in 1:length(clonotype.list)){

      HC_Vgene_usage[[i]] <- as.data.frame(table(clonotype.list[[i]]$HC_vgene))
      colnames(HC_Vgene_usage[[i]]) <- c("Vgene", "Frequency")
      for (j in 1:nrow(HC_Vgene_usage[[i]])){
        HC_Vgene_usage[[i]]$Percentage[j] <- HC_Vgene_usage[[i]]$Frequency[j]/sum(HC_Vgene_usage[[i]]$Frequency)*100
      }
      actual.gene.number <- HC.gene.number
      if(HC.gene.number > nrow(HC_Vgene_usage[[i]])){
        actual.gene.number <- nrow(HC_Vgene_usage[[i]])
      }
      #Rank based on most used V gene
      ranks <- order(-HC_Vgene_usage[[i]]$Frequency)
      HC_Vgene_usage[[i]] <- HC_Vgene_usage[[i]][ranks,]

      HC_Vgene_usage_plot[[i]] <- ggplot2::ggplot(HC_Vgene_usage[[i]][1:actual.gene.number,], ggplot2::aes(x=Vgene, y=Percentage, fill=Vgene)) + ggplot2::geom_bar(stat="identity", size=0.5, width=0.6, color="black", show.legend = FALSE) + ggplot2::theme_classic() + ggplot2::theme(axis.text.x = ggplot2::element_text(angle = 90, vjust = 0.5, hjust=1)) + ggplot2::ylab("% of unique clones") + ggplot2::xlab("") + ggplot2::theme(plot.title = ggplot2::element_text(hjust = 0.5)) + ggplot2::scale_y_continuous(expand = c(0,0)) + ggplot2::scale_color_gradient(low="blue", high="red") + ggplot2::ggtitle(paste0("IgH V gene usage - sample ",i)) + ggplot2::theme(text = ggplot2::element_text(size = 12))

    }

    #  }

    if(LC.Vgene==T){

      for (i in 1:length(clonotype.list)){

        LC_Vgene_usage[[i]] <- as.data.frame(table(clonotype.list[[i]]$LC_vgene))
        colnames(LC_Vgene_usage[[i]]) <- c("Vgene", "Frequency")
        for (j in 1:nrow(LC_Vgene_usage[[i]])){
          LC_Vgene_usage[[i]]$Percentage[j] <- LC_Vgene_usage[[i]]$Frequency[j]/sum(LC_Vgene_usage[[i]]$Frequency)*100
        }
        actual.gene.number <- LC.gene.number
        if(LC.gene.number > nrow(LC_Vgene_usage[[i]])){
          actual.gene.number <- nrow(LC_Vgene_usage[[i]])
        }
        #Rank based on most used V gene
        ranks <- order(-LC_Vgene_usage[[i]]$Frequency)
        LC_Vgene_usage[[i]] <- LC_Vgene_usage[[i]][ranks,]

        LC_Vgene_usage_plot[[i]] <- ggplot2::ggplot(LC_Vgene_usage[[i]][1:actual.gene.number,], ggplot2::aes(x=Vgene, y=Percentage, fill=Vgene)) + ggplot2::geom_bar(stat="identity", size=0.5, width=0.6, color="black", show.legend = FALSE) + ggplot2::theme_classic() + ggplot2::theme(axis.text.x = ggplot2::element_text(angle = 90, vjust = 0.5, hjust=1)) + ggplot2::ylab("% of unique clones") + ggplot2::xlab("") + ggplot2::theme(plot.title = ggplot2::element_text(hjust = 0.5)) + ggplot2::scale_y_continuous(expand = c(0,0)) + ggplot2::scale_color_gradient(low="blue", high="red") + ggplot2::ggtitle(paste0("IgK/L V gene usage - sample ",i)) + ggplot2::theme(text = ggplot2::element_text(size = 12))

      }

    }
    Vgene_usage_plot <- do.call(c, list(HC_Vgene_usage_plot, LC_Vgene_usage_plot))



    return(Vgene_usage_plot)

  } else if(platypus.version == "v3" & compare == FALSE){

    
    #filtering for max 1VDJ 1VJ chain
    VDJ.matrix <- subset(VDJ.matrix, Nr_of_VDJ_chains == 1 & Nr_of_VJ_chains == 1)
    
    
    clonotype.list <- list()
    if (group.by %in% names(VDJ.matrix)) {
      clonotype.list <- split(VDJ.matrix, VDJ.matrix[,group.by])
    } else{
      stop("Provide valid column name for group.by")
    }
    
    names(clonotype.list) <- unique(na.omit(VDJ.matrix[,group.by]))
    print(paste0("Group order: ", paste0(na.omit(unique(VDJ.matrix[,group.by])), collapse = " ; ")))
    
    
    for (i in 1:length(clonotype.list)){
      
      HC_Vgene_usage[[i]] <- as.data.frame(table(clonotype.list[[i]]$VDJ_vgene))
      colnames(HC_Vgene_usage[[i]]) <- c("Vgene", "Frequency")
      for (j in 1:nrow(HC_Vgene_usage[[i]])){
        HC_Vgene_usage[[i]]$Percentage[j] <- HC_Vgene_usage[[i]]$Frequency[j]/sum(HC_Vgene_usage[[i]]$Frequency)*100
      }
      actual.gene.number <- HC.gene.number
      if(HC.gene.number > nrow(HC_Vgene_usage[[i]]) | HC.gene.number == "all"){
        actual.gene.number <- nrow(HC_Vgene_usage[[i]])
      }
      #Rank based on most used V gene
      ranks <- order(-HC_Vgene_usage[[i]]$Frequency)
      HC_Vgene_usage[[i]] <- HC_Vgene_usage[[i]][ranks,]
      
      HC_Vgene_usage_plot[[i]] <- ggplot2::ggplot(HC_Vgene_usage[[i]][1:actual.gene.number,], ggplot2::aes(x=Vgene, y=Percentage, fill=Vgene)) + ggplot2::geom_bar(stat="identity", size=0.5, width=0.6, color="black", show.legend = FALSE) + ggplot2::theme_classic() + ggplot2::theme(axis.text.x = ggplot2::element_text(angle = 90, vjust = 0.5, hjust=1)) + ggplot2::ylab("% of unique clones") + ggplot2::xlab("") + ggplot2::theme(plot.title = ggplot2::element_text(hjust = 0.5)) + ggplot2::scale_y_continuous(expand = c(0,0)) + ggplot2::scale_color_gradient(low="blue", high="red") + ggplot2::ggtitle(paste0("IgH V gene usage - ",group.by," ",names(clonotype.list)[i])) + ggplot2::theme(text = ggplot2::element_text(size = 12))
      
    }
    
    #  }
    
    if(LC.Vgene==T){
      
      for (i in 1:length(clonotype.list)){
        
        LC_Vgene_usage[[i]] <- as.data.frame(table(clonotype.list[[i]]$VJ_vgene))
        colnames(LC_Vgene_usage[[i]]) <- c("Vgene", "Frequency")
        for (j in 1:nrow(LC_Vgene_usage[[i]])){
          LC_Vgene_usage[[i]]$Percentage[j] <- LC_Vgene_usage[[i]]$Frequency[j]/sum(LC_Vgene_usage[[i]]$Frequency)*100
        }
        actual.gene.number <- LC.gene.number
        if(LC.gene.number > nrow(LC_Vgene_usage[[i]]) | LC.gene.number == "all"){
          actual.gene.number <- nrow(LC_Vgene_usage[[i]])
        }
        #Rank based on most used V gene
        ranks <- order(-LC_Vgene_usage[[i]]$Frequency)
        LC_Vgene_usage[[i]] <- LC_Vgene_usage[[i]][ranks,]
        
        LC_Vgene_usage_plot[[i]] <- ggplot2::ggplot(LC_Vgene_usage[[i]][1:actual.gene.number,], ggplot2::aes(x=Vgene, y=Percentage, fill=Vgene)) + ggplot2::geom_bar(stat="identity", size=0.5, width=0.6, color="black", show.legend = FALSE) + ggplot2::theme_classic() + ggplot2::theme(axis.text.x = ggplot2::element_text(angle = 90, vjust = 0.5, hjust=1)) + ggplot2::ylab("% of unique clones") + ggplot2::xlab("") + ggplot2::theme(plot.title = ggplot2::element_text(hjust = 0.5)) + ggplot2::scale_y_continuous(expand = c(0,0)) + ggplot2::scale_color_gradient(low="blue", high="red") + ggplot2::ggtitle(paste0("IgK/L V gene usage - group ", names(clonotype.list)[i])) + ggplot2::theme(text = ggplot2::element_text(size = 12))
        
      }
      
    }
    Vgene_usage_plot <- do.call(c, list(HC_Vgene_usage_plot, LC_Vgene_usage_plot))
    
    return(Vgene_usage_plot)
    
  } else if(platypus.version == "v3" & compare == TRUE){
    VDJ.matrix  <- subset(VDJ.matrix, Nr_of_VDJ_chains == 1 & Nr_of_VJ_chains == 1)
    
    output <- list()
    
    #split the data by "group.by"
    if (group.by %in% names(VDJ.matrix)) {
      sample_split <- split(VDJ.matrix, VDJ.matrix[,group.by])
    } else{
      stop("Provide valid column name for group.by")
    }
    
    vdj_vgenes_per_clone  <- list()
    table_vdj_vgene<- list()
    
    
    for (i in 1:length(sample_split)){
      vdj_vgenes_per_clone[[i]] <- as.data.frame(dplyr::count(sample_split[[i]],sample_split[[i]]$VDJ_vgene, sample_split[[i]]$clonotype_id)) 
      names(vdj_vgenes_per_clone[[i]]) <- c("VDJ_vgene","clonotype_id","n")
      table_vdj_vgene[[i]] <- as.data.frame(table(vdj_vgenes_per_clone[[i]]$VDJ_vgene))
      table_vdj_vgene[[i]]$Freq<- as.numeric(table_vdj_vgene[[i]]$Freq/sum(table_vdj_vgene[[i]]$Freq))*100
      names(table_vdj_vgene[[i]]) <- c("VDJ_vgene",paste0(unique(sample_split[[i]][,group.by])))
    }
    
    
    table_vdj_vgene <- purrr::reduce(table_vdj_vgene,full_join, by = "VDJ_vgene") 
    table_vdj_vgene[is.na(table_vdj_vgene)] <- 0
    table_vdj_vgene$average <- rowMeans(table_vdj_vgene[,2:ncol(table_vdj_vgene)])
    table_vdj_vgene <- arrange(table_vdj_vgene,desc(average))
    
    if(HC.gene.number > nrow(table_vdj_vgene) | HC.gene.number == "all"){
      HC.gene.number <- nrow(table_vdj_vgene)
    }
    
    table_vdj_vgene <- table_vdj_vgene[1:HC.gene.number,1:(ncol(table_vdj_vgene)-1)]
    table_vdj_vgene_plot <-  gather(table_vdj_vgene,Groups, Clone_fraction, names(table_vdj_vgene)[2]:names(table_vdj_vgene)[ncol(table_vdj_vgene)])
    table_vdj_vgene_plot$VDJ_vgene <- factor(table_vdj_vgene_plot$VDJ_vgene , levels = table_vdj_vgene[rev(rownames(table_vdj_vgene)),]$VDJ_vgene)
    
    vdj_plot <- ggplot2::ggplot(table_vdj_vgene_plot, aes(VDJ_vgene, Clone_fraction)) +
      geom_col(aes(fill = Groups)) +
      facet_wrap(~ Groups,ncol = length(unique(table_vdj_vgene_plot$Groups))) +
      scale_fill_manual("", values = scales::hue_pal()(length(unique(table_vdj_vgene_plot$Groups))),guide="none") +
      coord_flip() + 
      theme_classic() +
      ylab("Fraction of clones (%)")+
      xlab("IGHV")
    
    output[[1]] <- list()
    output[[1]][[1]] <- vdj_plot
    output[[1]][[2]] <- table_vdj_vgene
    
    
    if(LC.Vgene==T){
      
      #split the data by "group.by"
      if (group.by %in% names(VDJ.matrix)) {
        sample_split <- split(VDJ.matrix, VDJ.matrix[,group.by])
      } else{
        stop("Provide valid column name for group.by")
      }
      
      vj_vgenes_per_clone  <- list()
      table_vj_vgene<- list()
      
      
      for (i in 1:length(sample_split)){
        vj_vgenes_per_clone[[i]] <- as.data.frame(dplyr::count(sample_split[[i]],sample_split[[i]]$VJ_vgene, sample_split[[i]]$clonotype_id)) 
        names(vj_vgenes_per_clone[[i]]) <- c("VJ_vgene","clonotype_id","n")
        table_vj_vgene[[i]] <- as.data.frame(table(vj_vgenes_per_clone[[i]]$VJ_vgene))
        table_vj_vgene[[i]]$Freq<- as.numeric(table_vj_vgene[[i]]$Freq/sum(table_vj_vgene[[i]]$Freq))*100
        names(table_vj_vgene[[i]]) <- c("VJ_vgene",paste0(unique(sample_split[[i]][,group.by])))
      }
      
      
      table_vj_vgene <- purrr::reduce(table_vj_vgene,full_join, by = "VJ_vgene") 
      table_vj_vgene[is.na(table_vj_vgene)] <- 0
      table_vj_vgene$average <- rowMeans(table_vj_vgene[,2:ncol(table_vj_vgene)])
      table_vj_vgene <- arrange(table_vj_vgene,desc(average))
      
      if(LC.gene.number > nrow(table_vj_vgene) | LC.gene.number == "all"){
        LC.gene.number <- nrow(table_vj_vgene)
      }
      
      table_vj_vgene <- table_vj_vgene[1:LC.gene.number,1:(ncol(table_vj_vgene)-1)]
      table_vj_vgene_plot <-  gather(table_vj_vgene,Groups, Clone_fraction, names(table_vj_vgene)[2]:names(table_vj_vgene)[ncol(table_vj_vgene)])
      #make sure levels are in the right order
      table_vj_vgene_plot$VJ_vgene <- factor(table_vj_vgene_plot$VJ_vgene , levels = table_vj_vgene[rev(rownames(table_vj_vgene)),]$VJ_vgene)
      
      
      vj_plot <- ggplot2::ggplot(table_vj_vgene_plot, aes(VJ_vgene, Clone_fraction)) +
        geom_col(aes(fill = Groups)) +
        facet_wrap(~ Groups,ncol = length(unique(table_vj_vgene_plot$Groups))) +
        scale_fill_manual("", values = scales::hue_pal()(length(unique(table_vj_vgene_plot$Groups))),guide="none") +
        coord_flip() + 
        theme_classic() +
        ylab("Fraction of clones (%)")+
        xlab("IGHV")
      output[[2]] <- list()
      output[[2]][[1]] <- vj_plot
      output[[2]][[2]] <- table_vj_vgene
      
    }
    return(output)
  }
}

